# -*- coding: utf-8 -*-
"""CIE-4..

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1w7BPoLa9DbDeN2mspOPjn4F1ZRFniTT3
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

#Load dataset
df=pd.read_csv('/content/Mall_Customers.csv')
df
x=df.iloc[:,[3,4]].values
# Standardize the features
x= StandardScaler().fit_transform(x)

#data pre-processing
Income_null=df['Annual Income (k$)'].isnull().sum()
df['Annual Income (k$)'].fillna(df['Annual Income (k$)'].mean(),inplace=True)
after_mean_Income=df['Annual Income (k$)'].isnull().sum()


#Finding the optimal no of clusters using elbow method
WCSS_list=[]
for i in range(1,11):
  kmeans=KMeans(n_clusters=i,init='k-means++',random_state=42)
  kmeans.fit(x)
  WCSS_list.append(kmeans.inertia_)

#Visualization
plt.plot(range(1,11),WCSS_list,marker='o')
plt.title("The Elbow method Graph")
plt.xlabel("Number of clusters")
plt.ylabel("WCSS_list")
plt.show()