# -*- coding: utf-8 -*-
"""CIE-3

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CvnRP31SleldUpFE3F_ffhEEf2vYdtyW
"""

import pandas as pd
df=pd.read_csv('/content/BostonHousing.csv')
#Data Exploration
df.head()

df.info()

df.describe()

df.isnull().sum()

df.duplicated().sum()

df.columns

#Perform preprocessing
zn_null=df['zn'].isnull().sum()
df['zn'].fillna(df['zn'].mean(),inplace=True)
after_mean_zn=df['zn'].isnull().sum()
print(zn_null)
print(after_mean_zn)

from sklearn.model_selection import train_test_split
x=df['age']
y=df['zn']
x_test,x_train,y_test,y_train=train_test_split(x,y,test_size=0.2,random_state=42)
print(x_test)
print(x_train)
print(y_test)
print(y_train)

#import libraries
import pandas as pd
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split

#load dataset
iris = load_iris()
# Data exploration
df.head()

df.info()

df.describe()

df.isnull().sum()

df.duplicated().sum()

#Perform preprocessing
PetalLengthCm_null=df['PetalLengthCm'].isnull().sum()
df['PetalLengthCm'].fillna(df['PetalLengthCm'].mean(),inplace=True)
after_mean_PetalLengthCm=df['PetalLengthCm'].isnull().sum()
print('PetalLengthCm_null:',PetalLengthCm_null)
print('after_mean_PetalLengthCm:',after_mean_PetalLengthCm)

#Data spliting
x=iris.data
y=iris.target
x_test,x_train,y_test,y_train=train_test_split(x,y,test_size=0.2,random_state=42)
print('x_test,x_train,y_test,y_train',x_test,x_train,y_test,y_train)

#Evaluation Metrics
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.linear_model import LinearRegression
model=LinearRegression()
model.fit(x_train,y_train)
y_pred=model.predict(x_test)
mse=mean_squared_error(y_test,y_pred)
r2_score=r2_score(y_test,y_pred)
print("Mean Squared erorr:",mse)
print("r2 score:",r2_score)