# -*- coding: utf-8 -*-
"""practicalExam.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZumA0sIDQKtxH-k9eWiftqzdks-PeBp0
"""

#Import the libraries
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score,mean_squared_error,classification_report
from sklearn.svm import SVC
from sklearn.datasets import load_iris

#Load the Iris dataset
df=load_iris()

#select features(x) and target variable(y)
x=df.data
y=df.target

#split the dataset into training set and testing set
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

#Create the svm model
model=SVC()

#Train the svm model
model.fit(x_train,y_train)

#Make predictions on test set
predictions=model.predict(x_test)

#Evaluate the model
mse=mean_squared_error(y_test,predictions)
print("mean_squared_error:",mse)

accuracy=accuracy_score(y_test,predictions)
print("accuracy:",accuracy)

#Display the classification report
print("Classification report:")
print(classification_report(y_test,predictions))